services:
  2fauth:
    container_name: 2fauth
    image: 2fauth/2fauth:latest
    restart: unless-stopped
    ports:
      - 8000:8000
    networks:
      - 2fauth
    volumes:
      - ${AUTH_DATA_PATH}:/2fauth:rw
    environment:
      - TRUSTED_PROXIES=*
      - APP_KEY=${APP_KEY}
      - APP_URL=${APP_URL}
      - ASSET_URL=${ASSET_URL}

networks:
  2fauth:
    driver: bridge