services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    ports:
      - 888:80
    networks:
      - vaultwarden
    environment:
      - SIGNUPS_ALLOWED=false
    volumes:
      - ${VAULTWARDEN_DATA_PATH}:/data:rw

networks:
  vaultwarden:
    driver: bridge