services:
  watchtower:
    container_name: watchtower
    image: nickfedor/watchtower:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /root/.docker/config.json:/config.json:ro
    environment:
      - TZ=${TZ}
      - WATCHTOWER_CLEANUP=${WATCHTOWER_CLEANUP}
      - WATCHTOWER_SCHEDULE=${WATCHTOWER_SCHEDULE}
      - WATCHTOWER_HTTP_API_METRICS=${WATCHTOWER_HTTP_API_METRICS}
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN}

networks:
  watchtower:
    driver: bridge